version: '3.9'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces
    environment:
      CARGO_TARGET_DIR: /tmp/target
    command: sleep infinity
